# Base image for building
FROM python:3.12-slim AS build
ARG APP_DIR=/src

# Install necessary packages
RUN apt-get update \
    && apt-get install -y \
         curl \
         build-essential \
         libffi-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Poetry
ENV POETRY_VERSION=1.5.1
RUN curl -sSL https://install.python-poetry.org | python - --version $POETRY_VERSION
ENV PATH /root/.local/bin:$PATH

WORKDIR ${APP_DIR}

COPY pyproject.toml poetry.lock ./
COPY . ./

RUN python -m venv --copies ${APP_DIR}/venv
RUN . ${APP_DIR}/venv/bin/activate && poetry install --only main

# Base image for running
FROM python:3.12-slim AS run
ARG APP_DIR=/src

# Copy the virtual environment from the build stage
COPY --from=build ${APP_DIR}/venv ${APP_DIR}/venv/
ENV PATH ${APP_DIR}/venv/bin:$PATH

WORKDIR ${APP_DIR}
COPY . ./

# Health check
HEALTHCHECK --start-period=30s CMD python -c "import requests; requests.get('http://localhost:8000/docs', timeout=2)"

CMD ["uvicorn", "backend.src.main:app", "--host", "0.0.0.0", "--port", "8000"]
